FROM php:8.4-fpm

ARG UID=1000
ARG GID=1000

COPY --from=composer:2.8 /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libpq-dev \
    libicu-dev \
    pkg-config \
    zip \
    unzip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pdo_pgsql pgsql mbstring exif pcntl bcmath gd zip intl \
    && groupmod -o -g ${GID} www-data \
    && usermod -o -u ${UID} -g www-data www-data \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*