<?php

/**
 * ISO 3166-1 alpha-2 country code list.
 * Single source of truth used across the application for country validation
 * and display in forms, APIs, and seeders.
 */
return [
    'AF' => 'Afghanistan',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AR' => 'Argentina',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BD' => 'Bangladesh',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BR' => 'Brazil',
    'BG' => 'Bulgaria',
    'CA' => 'Canada',
    'CL' => 'Chile',
    'CN' => 'China',
    'CO' => 'Colombia',
    'HR' => 'Croatia',
    'CZ' => 'Czech Republic',
    'DK' => 'Denmark',
    'EG' => 'Egypt',
    'EE' => 'Estonia',
    'FI' => 'Finland',
    'FR' => 'France',
    'DE' => 'Germany',
    'GR' => 'Greece',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'JP' => 'Japan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KR' => 'South Korea',
    'KG' => 'Kyrgyzstan',
    'LV' => 'Latvia',
    'LT' => 'Lithuania',
    'MY' => 'Malaysia',
    'MX' => 'Mexico',
    'NL' => 'Netherlands',
    'NZ' => 'New Zealand',
    'NG' => 'Nigeria',
    'NO' => 'Norway',
    'PK' => 'Pakistan',
    'PH' => 'Philippines',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'SA' => 'Saudi Arabia',
    'RS' => 'Serbia',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'ZA' => 'South Africa',
    'ES' => 'Spain',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TH' => 'Thailand',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'US' => 'United States',
    'UZ' => 'Uzbekistan',
    'VN' => 'Vietnam',
];
